apiVersion: v1
kind: Service
metadata:
  name: {{ include "clamav.fullname" . }}
  labels:
    {{- include "clamav.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: clamav
      protocol: TCP
      name: clamav
  selector:
    {{- include "clamav.selectorLabels" . | nindent 4 }}

